spring.application.name=footnest-backend

spring.datasource.url=jdbc:sqlite:footnest.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.static-locations=file:uploads/

app.base-url=http://localhost:8080
